# Generated by Django 6.0.5 on 2026-05-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='profiles/default_profile_image.jfif', upload_to='profiles'),
        ),
    ]
